
# restore_model: ''
restore_model: ./pretrained/fastpitch_ar_adv.pth
# restore_model: ./checkpoints/exp0/states.pth

log_dir: logs/exp1
checkpoint_dir: checkpoints/exp1

train_wavs_path: G:/data/arabic-speech-corpus/wav_new
train_labels: ./data/train_phon.txt

test_wavs_path: G:/data/arabic-speech-corpus/test set/wav_new
test_labels: ./data/test_phon.txt

# for fastpitch
f0_dict_path: ./data/wav_f0_dict.pt

balanced_sampling: False
sampler_weights_file: ./data/sampler/sampler_weights

cache_dataset: False

n_save_states_iter: 100
n_save_backup_iter: 1000

learning_rate: 1.0e-4

f0_mean: 130.05478
f0_std: 22.86267